# .github/workflows/ci-cd.yml
name: CI/CD Pipeline
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.build.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v4
        name: Code checkout
      - name: Build and Push
        id: build
        uses: ./.github/actions/build-and-push
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ghcr.io/${{ github.repository }}
